### ISSUE TITLE
Question about the feature of GTEA and BEOID?

### ISSUE THREAD

**Issue by PHDJieFu** [Flowerfan/SF-Net#16]
Hello, thanks for your interesting work SF-Net!
I have some detail question about the feature of the dataset GTEA and BEOID: 
I notice that the feature dimension of each video is T*2048. From this paper, I get that this feature contains two parts (flow and RGB features). Can you tell me which part of the feature is the optical flow feature and which part is the RGB feature? Thanks for your help!

**Comment by Flowerfan** [comment]
Hi Jiefu,

The RGB feature is contained in the first 1024 dimension.

**Comment by PHDJieFu** [comment]
> The RGB feature is contained in the first 1024 dimension.

Ok, the rest 1024 dimension is the flow feature?
Thanks for your reply!
