### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by limjaebin** [Flowerfan/SF-Net#18]
hi, thank you for publishing this paper.

As I read this paper, I have a question.

1. Can I know the model used in Table 1 and the model used to measure Full in Table 3 ?

2. Can I know what hit means in Table 1 ?

Thank you for answering

**Comment by Flowerfan** [comment]
1. The model trained with human single frame annotations in Table 1 is the model in the last low of Table 3.  You can get the model by running ``python main.py``. The model is a bit better than the model in the original paper.
2. Hit is the new metric we proposed for single frame evaluation. For each detected action instance, we select the single frame of highest actionness score for testing. Hit means the selected action frame is in the time range of groundtruth. You can also check the code for more details.

**Comment by limjaebin** [comment]
Thank you for answering my questions :) !
