### ISSUE TITLE
video-dataset-issues

### ISSUE THREAD

**Issue by sc-56** [Flowerfan/SF-Net#19]
Dear author,

thanks for the great work, and when i set up all the env to test the code, i encounter with some issues, mostly happened in "video_dataset.py":

```
data = pd.read_csv(os.path.join(annotation_dire, filename), names=[
  File "/home/sc/anaconda3/envs/data/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper

pandas.errors.ParserError: Too many columns specified: expected 3 and found 1
```

Do you have any idea about solving this?

Thanks a lot for the support.
sc

**Comment by Flowerfan** [comment]
You may need to check the pandas version and the file content.
