### ISSUE TITLE
Could you please provide the Baidu Disk link?

### ISSUE THREAD

**Issue by liming-ai** [Flowerfan/SF-Net#6]
Due to some reasons, I cannot download the extracted features from google driven, especially for thumos, so could you please provide the baidu disk link for extracted features? Thanks very much!

**Comment by yangjiangeyjg** [comment]
> 
>请问你获取到数据了吗
> Due to some reasons, I cannot download the extracted features from google driven, especially for thumos, so could you please provide the baidu disk link for extracted features? Thanks very much!
