### ISSUE TITLE
Much higher performances are obtained on BEOID.

### ISSUE THREAD

**Issue by Pilhyeon** [Flowerfan/SF-Net#7]
Hello, thanks for sharing the implementation of this excellent work.

I have a question about the performance on BEOID.

When I run your code for the 2000 iterations as the paper specifies, the model scored a score of 11 % at the threshold of 0.7.

However, the reported score in your paper is much lower, which is 3.5 % of mAP@0.7.

Could you please explain why the gap exists and the model is underestimated in the paper?

Thanks!

**Comment by Flowerfan** [comment]
Thank you for your interest in our work. After submission, I have modified default hyperparameters to obtain better performance at higher IoU thresholds on THUMOS14.  We achieved 10.87 % of mAP@0.7 with the released code, which is 9.6% in the paper. Maybe this also improves the performance on BEOID.

**Comment by Pilhyeon** [comment]
Thanks for the quick reply!

I would add the improved result as well for comparison.

Nice work, again!
